#!/usr/bin/env python3

import argparse
import re
from pathlib import Path


SYMBOL_PATTERN = re.compile(r"extern Addr (_[A-Za-z0-9]+SegmentRom(Start|End));")
NAME_PATTERN = re.compile(r"^\s*-\s+name:\s*([A-Za-z0-9_]+)\s*$")
START_PATTERN = re.compile(r"^\s*start:\s*(0x[0-9A-Fa-f]+)\s*$")
FINAL_PATTERN = re.compile(r"^\s*-\s*\[\s*(0x[0-9A-Fa-f]+)\s*\]\s*$")


# These are name mismatches between hm64/include/ld_symbols.h and splat.us.yaml.
ALIASES = {
    "logossAssetsIndex": "logosAssetsIndex",
    "logossTextures": "logosTexture",
    "vegetableFestival": "squareFireworks",
    "village1Cutscenes": "cutsceneBank8",
}

# This segment exists in ld_symbols.h but the current splat file only exposes
# emptyOverlayScreen2/3/4. The missing symbol occupies the small gap between the
# checkerboard assets index and emptyOverlayScreen2Texture.
SPECIAL_RANGES = {
    "emptyOverlayScreen1Texture": (0x00CC9330, 0x00CC9350),
}


def parse_needed_symbols(header_path: Path):
    text = header_path.read_text()
    symbols = {}
    for full_name, edge in SYMBOL_PATTERN.findall(text):
        if full_name.endswith("SegmentRomStart"):
            base_name = full_name[len("_") : -len("SegmentRomStart")]
        else:
            base_name = full_name[len("_") : -len("SegmentRomEnd")]
        symbols.setdefault(base_name, set()).add(edge)
    return symbols


def parse_splat_ranges(splat_path: Path):
    entries = []
    current_name = None
    final_rom_end = None

    for line in splat_path.read_text().splitlines():
        if match := NAME_PATTERN.match(line):
            current_name = match.group(1)
            continue

        if match := START_PATTERN.match(line):
            if current_name is not None:
                entries.append((current_name, int(match.group(1), 16)))
                current_name = None
            continue

        if match := FINAL_PATTERN.match(line):
            final_rom_end = int(match.group(1), 16)

    if final_rom_end is None:
        raise RuntimeError(f"Could not find final ROM size sentinel in {splat_path}")

    ranges = {}
    for index, (name, start) in enumerate(entries):
        if index + 1 < len(entries):
            end = entries[index + 1][1]
        else:
            end = final_rom_end
        ranges[name] = (start, end)

    return ranges


def resolve_range(name: str, ranges):
    if name in SPECIAL_RANGES:
        return SPECIAL_RANGES[name]
    if name in ALIASES:
        return ranges[ALIASES[name]]
    return ranges.get(name)


def emit_symbol(lines, symbol_name: str, value: int):
    macho_symbol = f"_{symbol_name}"
    elf_symbol = symbol_name
    lines.extend(
        [
            "#if defined(__APPLE__)",
            f'__asm__(".globl {macho_symbol}\\n.set {macho_symbol}, 0x{value:08X}");',
            "#else",
            f'__asm__(".globl {elf_symbol}\\n.set {elf_symbol}, 0x{value:08X}");',
            "#endif",
        ]
    )


def emit_windows_symbol(lines, symbol_name: str, value: int):
    lines.append(f"#define {symbol_name} (*(Addr*)(uintptr_t)0x{value:08X})")


def render_c_source(symbols, ranges):
    lines = [
        "// Generated by hm64/tools/generate_rom_symbol_asm.py",
        "// Absolute symbols preserve N64-style '&_segmentRomStart' semantics on host.",
        "",
    ]

    missing = []
    for name in sorted(symbols):
        resolved = resolve_range(name, ranges)
        if resolved is None:
            missing.append(name)
            continue

        start, end = resolved
        if "Start" in symbols[name]:
            symbol = f"_{name}SegmentRomStart"
            emit_symbol(lines, symbol, start)
        if "End" in symbols[name]:
            symbol = f"_{name}SegmentRomEnd"
            emit_symbol(lines, symbol, end)
        lines.append("")

    if missing:
        missing_list = ", ".join(missing[:20])
        if len(missing) > 20:
            missing_list += ", ..."
        raise RuntimeError(f"Missing ROM ranges for {len(missing)} symbols: {missing_list}")

    return "\n".join(lines).rstrip() + "\n"


def render_windows_header(symbols, ranges):
    lines = [
        "// Generated by hm64/tools/generate_rom_symbol_asm.py",
        "// Windows fallback macros preserve '&_segmentRomStart' semantics without linker-defined absolute symbols.",
        "#ifndef _HM64_ROM_SYMBOL_OVERRIDES_H_",
        "#define _HM64_ROM_SYMBOL_OVERRIDES_H_",
        "",
        "#include <stdint.h>",
        "",
    ]

    missing = []
    for name in sorted(symbols):
        resolved = resolve_range(name, ranges)
        if resolved is None:
            missing.append(name)
            continue

        start, end = resolved
        if "Start" in symbols[name]:
            emit_windows_symbol(lines, f"_{name}SegmentRomStart", start)
        if "End" in symbols[name]:
            emit_windows_symbol(lines, f"_{name}SegmentRomEnd", end)

    if missing:
        missing_list = ", ".join(missing[:20])
        if len(missing) > 20:
            missing_list += ", ..."
        raise RuntimeError(f"Missing ROM ranges for {len(missing)} symbols: {missing_list}")

    lines.extend(["", "#endif"])
    return "\n".join(lines).rstrip() + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--ld-header", required=True)
    parser.add_argument("--splat-config", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    header_path = Path(args.ld_header)
    splat_path = Path(args.splat_config)
    output_path = Path(args.output)

    symbols = parse_needed_symbols(header_path)
    ranges = parse_splat_ranges(splat_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    if output_path.suffix.lower() == ".h":
        output_path.write_text(render_windows_header(symbols, ranges))
    else:
        output_path.write_text(render_c_source(symbols, ranges))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
